#!/bin/bash

# rep_get_file <file handle> [file]
if [ -z "$2" ]; then
    python3 ./client.py -k rep_pub_key.pem -r 127.0.0.1:5000 -c rep_get_file "$1"
else
    python3 ./client.py -k rep_pub_key.pem -r 127.0.0.1:5000 -c rep_get_file "$1" "$2"
fi