import unidecode
import re
import pycountry


UNIQUE_PEOPLE_NAMES = {
    'julio', 'miguel', 'manuel', 'domingos', 'joao', 'ricardo', 'silva', 'paulo', 'alverca', 'matos', 'carlos', 'dias', 
    'carvalho', 'de', 'monteiro', 'joel', 'maria', 'marques', 'joaquim', 'santos', 'torres', 'jorge', 'roberto', 'fernando',
    'machado', 'oliveira', 'pereira', 'martins', 'reis', 'rafael', 'dos', 'lima', 'rodrigues', 'teixeira', 'angeja', 'antonio', 
    'francisco', 'rouxinol', 'barbosa', 'ramos', 'ferreira', 'costa', 'luis', 'viegas', 'alberto', 'silveira', 'gomes', 'soares', 
    'ribeiro', 'lda', 'rilho', 'rodrigo', 'melo', 'ernesto', 'madeira', 'nascimento', 'moutela', 'rocha', 'alves', 'simoes', 
    'jose', 'pinto', 'almeida'
}

STOP_WORDS = {
    "rua","street","estrada","avenida","edif","largo","lda","av","zona"
}

TRANSLATION_TABLE = {
    "ldarua": "lda rua",
    "to the order of": "",
    "the order of": "",
    "to te order": "",
    "to order": "",
    "to order of": "",
    "the order": "",
    "colimited": "co",
    "coltd": "co",
    "colim": "co",
    "colimi": "co",
    "colimite": "co",
    "corporation":"corp",
    "distribuidora": "dist",
    "distribution": "dist",
    "distributors": "dist",
    "distri": "dist",
    "distrib": "dist",
    "distribeaute": "dist",
    "distribu": "dist",
    "distribucija": "dist",
    "distribucion": "dist",
    "distribucione": "dist",
    "distribuciones": "dist",
    "distribucionsl": "dist",
    "distribuction": "dist",
    "distribui": "dist",
    "distribuic": "dist",
    "distribuica": "dist",
    "distribuicao": "dist",
    "distribuicaorodovia": "dist",
    "distribuida": "dist",
    "distribuido": "dist",
    "distribuidor": "dist",
    "distribuidores": "dist",
    "distributeck": "dist",
    "distributers": "dist",
    "distributeur": "dist",
    "distributeurs": "dist",
    "distributie": "dist",
    "distributiecentrum": "dist",
    "distributing": "dist",
    "distributio": "dist",
    "distributions": "dist",
    "distributon": "dist",
    "distributor": "dist",
    "distributora": "dist",
    "distribuzione": "dist",
    "export": "exp",
    "exportacao": "exp",
    "exportadora": "exp",
    "exports": "exp",
    "eexport": "exp",
    "eexportacao": "exp",
    "eexportadora": "exp",
    "exporta": "exp",
    "exportac": "exp",
    "exportaca": "exp",
    "exportacaltda": "exp",
    "exportacaode": "exp",
    "exportacaoindustria": "exp",
    "exportacaoltda": "exp",
    "exportacaoplasticos": "exp",
    "exportacion": "exp",
    "exportaciones": "exp",
    "exportaco": "exp",
    "exportacoes": "exp",
    "exportad": "exp",
    "exportador": "exp",
    "exportadoracomercio": "exp",
    "exportadores": "exp",
    "exportap": "exp",
    "exportation": "exp",
    "exporte": "exp",
    "exporter": "exp",
    "exporters": "exp",
    "exportimport": "exp",
    "exporting": "exp",
    "exportlda": "exp",
    "exportltda": "exp",
    "exportplantain": "exp",
    "exportsarua": "exp",
    "exportsl": "exp",
    "exportss": "exp",
    "import": "imp",
    "importacao": "imp",
    "importaciones": "imp",
    "importadora": "imp",
    "imports": "imp",
    "import&": "imp",
    "import&expor": "imp",
    "import&export": "imp",
    "importa": "imp",
    "importac": "imp",
    "importaca": "imp",
    "importacdora": "imp",
    "importacion": "imp",
    "importacionesexportaciones": "imp",
    "importacionsl": "imp",
    "importacoes": "imp",
    "importacrodovia": "imp",
    "importadara": "imp",
    "importador": "imp",
    "importadoracomercializadora": "imp",
    "importadores": "imp",
    "importados": "imp",
    "importanciones": "imp",
    "importao": "imp",
    "importation": "imp",
    "importcargo": "imp",
    "importe": "imp",
    "imported": "imp",
    "importer": "imp",
    "importers": "imp",
    "importeur": "imp",
    "importexport": "imp",
    "importexportdivers": "imp",
    "importexportfresia": "imp",
    "importexportinc": "imp",
    "importhandels": "imp",
    "importing": "imp",
    "importlab": "imp",
    "importlogistik": "imp",
    "importsllc": "imp",
    "industria": "ind",
    "industrial": "ind",
    "industriales": "ind",
    "industrias": "ind",
    "industries": "ind",
    "industry": "ind",
    "industr": "ind",
    "industra": "ind",
    "industral": "ind",
    "industrales": "ind",
    "industri": "ind",
    "industriaavenida": "ind",
    "industriade": "ind",
    "industriais": "ind",
    "industriaislda": "ind",
    "industrial&trade": "ind",
    "industrial&trading": "ind",
    "industriale": "ind",
    "industriali": "ind",
    "industrializacao": "ind",
    "industrializados": "ind",
    "industrials": "ind",
    "industrialsauce": "ind",
    "industriasbeco": "ind",
    "industriatextil": "ind",
    "industrie": "ind",
    "industriel": "ind",
    "industrielle": "ind",
    "industrielles": "ind",
    "industriels": "ind",
    "industrierader": "ind",
    "industrious": "ind",
    "industry&trade": "ind",
    "industrycoltd": "ind",
    "industryltd": "ind",
    "industrytrade": "ind",
    "industy": "ind",
    "internacionais": "int",
    "internacional": "int",
    "internacionales": "int",
    "international": "int",
    "internaational": "int",
    "internac": "int",
    "internaci": "int",
    "internaciavdrantunes": "int",
    "internacio": "int",
    "internacion": "int",
    "internaciona": "int",
    "internacionai": "int",
    "internacionaiscomplexo": "int",
    "internacionaiseirelime": "int",
    "internacionaislda": "int",
    "internacionaisltda": "int",
    "internacionaisrua": "int",
    "internacionalav": "int",
    "internacionalltda": "int",
    "internacionalltdarua": "int",
    "internacionalnorpatagonico": "int",
    "internacionalr": "int",
    "internacionalrua": "int",
    "internacionals": "int",
    "internacionalsa": "int",
    "internacionalsl": "int",
    "internaional": "int",
    "internal": "int",
    "internancional": "int",
    "internantional": "int",
    "internasional": "int",
    "internatio": "int",
    "internationa": "int",
    "internationalafrica": "int",
    "internationalbeijing": "int",
    "internationalchicago": "int",
    "internationale": "int",
    "internationaler": "int",
    "internationalespeditionsges": "int",
    "internationalhk": "int",
    "internationalhklimited": "int",
    "internationali": "int",
    "internationalinc": "int",
    "internationalllc": "int",
    "internationallouisville": "int",
    "internationalltd": "int",
    "internationalltda": "int",
    "internationalltdarua": "int",
    "internationally": "int",
    "internationalnyinc": "int",
    "internationaloverseaspteltd": "int",
    "internationalqingdaocoltd": "int",
    "internationalsl": "int",
    "internationaltdanr": "int",
    "internationaltrade": "int",
    "internationaltransportes": "int",
    "internationaux": "int",
    "internationl": "int",
    "internatonal": "int",
    "internazionali": "int",
    "lda": "ltd",
    "limitada": "ltd",
    "limited": "ltd",
    "limi": "ltd",
    "limit": "ltd",
    "limita": "ltd",
    "limitad": "ltd",
    "limitadahead": "ltd",
    "limitata": "ltd",
    "limite": "ltd",
    "limitedahmedabad": "ltd",
    "limiteddelhimahipalpur": "ltd",
    "limitedexport": "ltd",
    "limitedhyderabad": "ltd",
    "limitedigloo": "ltd",
    "limitedmumbai": "ltd",
    "limitednew": "ltd",
    "limitedpspdbcm": "ltd",
    "limitedqingdao": "ltd",
    "limitedshenzhen": "ltd",
    "limitedvisakhapatnam": "ltd",
    "limitee": "ltd",
    "limits": "ltd",
    "limitted": "ltd",
    "llc": "ltd",
    "ltda": "ltd",
    "ltdsti": "ltd",
    "logistic": "log",
    "logistica": "log",
    "logistics": "log",
    "lojistik": "log",
    "logistic&tradingguangzhoucoltd": "log",
    "logisticaaduaneira": "log",
    "logisticaav": "log",
    "logisticaeireli": "log",
    "logisticainternacional": "log",
    "logistical": "log",
    "logisticaltda": "log",
    "logisticas": "log",
    "logisticasenza": "log",
    "logisticasintegradas": "log",
    "logisticdr": "log",
    "logisticke": "log",
    "logistico": "log",
    "logisticos": "log",
    "logisticosltda": "log",
    "logisticsag": "log",
    "logisticschina": "log",
    "logisticschinacoltd": "log",
    "logisticschinacoltddalia": "log",
    "logisticschinacoltdtianjin": "log",
    "logisticschinalimited": "log",
    "logisticschinaltdqingdao": "log",
    "logisticscnpj": "log",
    "logisticsdalian": "log",
    "logisticsdaliancoltd": "log",
    "logisticsdalianinc": "log",
    "logisticseuropegmbh": "log",
    "logisticsguangzhoucoltd": "log",
    "logisticsiberica": "log",
    "logisticsinc": "log",
    "logisticsincqingdao": "log",
    "logisticsincshenzhen": "log",
    "logisticsllc": "log",
    "logisticsltd": "log",
    "logisticsonemovingonemovingcombr": "log",
    "logisticsportugal": "log",
    "logisticsprivatelimited": "log",
    "logisticsprocurementcalifornia": "log",
    "logisticsptyltd": "log",
    "logisticsqingdao": "log",
    "logisticsqingdaocolt": "log",
    "logisticsqingdaocoltd": "log",
    "logisticsreconquista": "log",
    "logisticsrua": "log",
    "logisticssanta": "log",
    "logisticssau": "log",
    "logisticsshanghai": "log",
    "logisticsshanghailimited": "log",
    "logisticsshenzhen": "log",
    "logisticsshenzhenltd": "log",
    "logisticssl": "log",
    "logisticssrl": "log",
    "logisticstianjincoltd": "log",
    "logisticstoronto": "log",
    "logisticsxiamen": "log",
    "logistiek": "log",
    "logistify": "log",
    "logistik": "log",
    "logistika": "log",
    "logistique": "log",
    "logistiques": "log",
    "logistiszentrum": "log",
    "logistix": "log",
    "logistocs": "log",
    "logistom": "log",
    "logistransporte": "log",
    "logisturk": "log",
    "logistyczne": "log",
    "logistyka": "log",
    "service": "ser",
    "services": "ser",
    "servicios": "ser",
    "servicos": "ser",
    "transitarios": "trans",
    "transitos": "trans",
    "transport": "trans",
    "transportation": "trans",
    "transporte": "trans",
    "transportes": "trans",
    "transintercargo": "trans",
    "transistmica": "trans",
    "transit": "trans",
    "transitainer": "trans",
    "transitaire": "trans",
    "transitar": "trans",
    "transitari": "trans",
    "transitario": "trans",
    "transitarioslda": "trans",
    "transitariosldarua": "trans",
    "transitariosrua": "trans",
    "transitariossa": "trans",
    "transitariossarua": "trans",
    "transitariossociedade": "trans",
    "transitariosunipessoa": "trans",
    "transitarirua": "trans",
    "transitaruios": "trans",
    "transitex": "trans",
    "transitextransitos": "trans",
    "transito": "trans",
    "transitrios": "trans",
    "transitrioslda": "trans",
    "transits": "trans",
    "transityre": "trans",
    "forw": "fwd",
    "forw&": "fwd",
    "forwa": "fwd",
    "forwader": "fwd",
    "forwading": "fwd",
    "forwar": "fwd",
    "forward": "fwd",
    "forwarder": "fwd",
    "forwarders": "fwd",
    "forwardershenzhenltd": "fwd",
    "forwardershenzhenltdwuhan": "fwd",
    "forwardersinc": "fwd",
    "forwarderssa": "fwd",
    "forwardersshanghaicoltdningbo": "fwd",
    "forwarderszltdguangzhou": "fwd",
    "forwardi": "fwd",
    "forwardin": "fwd",
    "forwarding": "fwd",
    "forwardingbrazil": "fwd",
    "forwardingbrazillogistics": "fwd",
    "forwardingbrl": "fwd",
    "forwardingchinaltd": "fwd",
    "forwardingcolombia": "fwd",
    "forwardingfrance": "fwd",
    "forwardinggu": "fwd",
    "forwardingguangzhou": "fwd",
    "forwardinggzlimited": "fwd",
    "forwardinghk": "fwd",
    "forwardingllc": "fwd",
    "forwardingmontivilliers": "fwd",
    "forwardingqingdao": "fwd",
    "forwardingrua": "fwd",
    "forwardingsa": "fwd",
    "forwardingshang": "fwd",
    "forwardingshanghaicoltd": "fwd",
    "forwardingshanghailtdxiamen": "fwd",
    "forwardingtianjin": "fwd",
    "forwards": "fwd",
    "forwariding": "fwd",
    "forwartrans": "fwd",
    "forwrding": "fwd"
}


def is_person_name(name):
    return all(n in UNIQUE_PEOPLE_NAMES for n in name.split())


def clean_name(name):
    name = unidecode.unidecode(name.lower())
    name = re.sub(r'-', ' - ', name)
    name = re.sub(r'\s+', ' ', name).strip()

    for k, v in TRANSLATION_TABLE.items():
        name = name.replace(k, v)
    
    for i in STOP_WORDS:
        if i in name:
            name = name[:name.find(i)]

    countries = {i.name.lower() for i in pycountry.countries}

    for j in countries:
        name = re.sub(j,'',name)

    name = re.sub(r'[^a-z0-9 ]+', '', name)
    return re.sub(r'\s+', ' ', name).strip()