#!/bin/bash

# Define file paths
DB_FILE="analysis.db"
QUERY_FILE="querys.sql"
DEPARTURE_OUTPUT_FILE="DepartureToCorrect.txt"
TRANSPORT_OUTPUT_FILE="TransportToCorrect.txt"

# Check if the database file exists
if [ ! -f "$DB_FILE" ]; then
    echo "Error: Database file '$DB_FILE' not found."
    exit 1
fi

# Remove the output file if it exists
rm -f "$DEPARTURE_OUTPUT_FILE"
rm -f "$TRANSPORT_OUTPUT_FILE"

# Run the querys to de Departure and Transport tables
echo "Query results: " >> "$DEPARTURE_OUTPUT_FILE"
sqlite3 "$DB_FILE" 'SELECT "Name","Standard Name","Standard Short Name" FROM "Departure-notCorrected" WHERE "NIF in Standard" = 1;' >> "$DEPARTURE_OUTPUT_FILE"
echo "Output saved to $DEPARTURE_OUTPUT_FILE"

echo "Query results: " >> "$TRANSPORT_OUTPUT_FILE"
sqlite3 "$DB_FILE" 'SELECT "Name","Standard Name","Standard Short Name" FROM "Transport-notCorrected" WHERE "NIF in Standard" = 1;' >> "$TRANSPORT_OUTPUT_FILE"
echo "Output saved to $TRANSPORT_OUTPUT_FILE"