#!/bin/bash

# Definir cores
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
MAGENTA="\033[1;35m"
CYAN="\033[1;36m"
RESET="\033[0m"

# Remover ficheiros de testes passados
echo $'\n'
echo -e "${YELLOW}Remover ficheiros e pastas de testes passados${RESET}"

if test -f Subject_A_keys.json; then
    rm Subject_A_keys.json
    echo "--> Ficheiro 'Subject_A_keys.json' removido."
    sleep 0.1
fi

if test -f Subject_B_keys.json; then
    rm Subject_B_keys.json
    echo "--> Ficheiro 'Subject_B_keys.json' removido."
    sleep 0.1
fi

if test -f Subject_A_session.json; then
    rm Subject_A_session.json
    echo "--> Ficheiro 'Subject_A_session.json' removido."
    sleep 0.1
fi

if test -f Subject_B_session.json; then
    rm Subject_B_session.json
    echo "--> Ficheiro 'Subject_B_session.json' removido."
    sleep 0.1
fi

if test -f rep_pub_key.pem; then
    rm rep_pub_key.pem
    echo "--> Ficheiro 'rep_pub_key.pem' removido."
    sleep 0.1
fi

if test -f test_file_10Kb; then
    rm test_file_10Kb
    echo "--> Ficheiro 'test_file_10Kb' removido."
    sleep 0.1
fi

if test -f test_file_100Kb; then
    rm test_file_100Kb
    echo "--> Ficheiro 'test_file_100Kb' removido."
    sleep 0.1
fi

if test -f test_file_1Mb; then
    rm test_file_1Mb
    echo "--> Ficheiro 'test_file_1Mb' removido."
    sleep 0.1
fi

if test -d repository/docs; then
    rm -rf repository/docs
    echo "--> Pasta 'repository/docs' removida."
    sleep 0.1
fi

if test -f repository/documents.json; then
    rm repository/documents.json
    echo "--> Ficheiro 'repository/documents.json' removido."
    sleep 0.1
fi

if test -f repository/organizations.json; then
    rm repository/organizations.json
    echo "--> Ficheiro 'repository/organizations.json' removido."
    sleep 0.1
fi

if test -f repository/sessions.json; then
    rm repository/sessions.json
    echo "--> Ficheiro 'repository/sessions.json' removido."
    sleep 0.1
fi

if test -f repository/rep_priv_key.pem; then
    rm repository/rep_priv_key.pem
    echo "--> Ficheiro 'repository/rep_priv_key.pem' removido."
    sleep 0.1
fi

if test -f repository/rep_pub_key.pem; then
    rm repository/rep_pub_key.pem
    echo "--> Ficheiro 'repository/rep_pub_key.pem' removido."
    sleep 0.1
fi