#!/bin/bash

FILE_FOLDER=$(dirname $0)

# rep_remove_permission <session file> <role> <username/permission>
python3 ${FILE_FOLDER}/../client.py -k rep_pub_key.pem -r 127.0.0.1:5000 -c rep_remove_permission $1 $2 $3