#!/bin/bash

FILE_FOLDER=$(dirname $0)

# rep_add_subject <session file> <username> <name> <email> <credentials file>
python3 ${FILE_FOLDER}/../client.py -k rep_pub_key.pem -r 127.0.0.1:5000 -c rep_add_subject $1 $2 $3 $4 $5
