#!/bin/bash

FILE_FOLDER=$(dirname $0)

# rep_list_permission_roles <session file> <permission>
python3 ${FILE_FOLDER}/../client.py -k rep_pub_key.pem -r 127.0.0.1:5000 -c rep_list_permission_roles $1 $2